### PR TITLE
fix: incomplete multi-part checkpoint handling when no hint is provided

### LINKED ISSUE #497: Log file listing should handle incomplete multi-part checkpoints
### Describe the bug

When constructing a `LogSegment`, we scan the `_delta_log` directory for checkpoints and commits. The most recent checkpoint is collected from the log, but the kernel does not check that it has collected a full multi-part checkpoint. Thus, the checkpoint returned may be incomplete.

### To Reproduce

This behaviour can be seen in the LogSegment test `build_snapshot_with_missing_checkpoint_part_no_hint`.

### Expected behavior

`build_snapshot_with_missing_checkpoint_part_no_hint` should pass and return the most recent *complete* checkpoint at version 3.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sebastiantia**
## What changes are proposed in this pull request?

**Problem behavior:**
When constructing a `LogSegment`, we scan the `_delta_log` directory for checkpoints and commits. The most recent checkpoint is collected from the log, but the kernel does not check that it has collected a full multi-part checkpoint. Thus, the checkpoint returned may be incomplete. More context can be found here  #497

**Expected behavior:**
Keep track of the most recent _complete_ checkpoint when iterating through the `_delta_log` directory.
`build_snapshot_with_out_of_date_last_checkpoint` showcases the expected behavior, which now passes ✅ .

To accomplish this, we group log files by version, and then group checkpoint parts according to the checkpoint they belong to, (as there can exist multiple checkpoints per version). We then take an arbitrary _complete_ checkpoint for a version if one exists and keep track of the most recent _complete_ checkpoint. We also clear collected commit files once we have discovered a complete checkpoint as we only need to retain commit files with version **greater** than the checkpoint's version.

## How was this change tested?

- `build_snapshot_with_out_of_date_last_checkpoint` is the intended behavior of scenario described in #497
- `build_snapshot_with_out_of_date_last_checkpoint_and_incomplete_recent_checkpoint`. _Prior_ to this PR, when an out of date checkpoint hint is provided, AND there is a more recent incomplete checkpoint, the more recent incomplete checkpoint would be taken and assumed to be complete - resulting in errors building the snapshot. _Now_, the more recent incomplete checkpoint is ignored.
- `build_snapshot_with_unsupported_uuid_checkpoint` verifies that currently unsupported `UuidCheckpoint`s are not considered valid checkpoints.
- `build_snapshot_with_multiple_incomplete_multipart_checkpoints` verifies that _multiple_ incomplete multi-part checkpoints that interleave are validated appropriately, more context here: https://github.com/delta-io/delta-kernel-rs/pull/641#discussion_r1915552447

resolves #497

### CODE REVIEW

File: kernel/src/log_segment/delta_log_group_iterator.rs [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+                        version = Some(next_path.version);
+                    }
+
+                    if let Ok(path) = self.iter.next().unwrap() {
+                        paths.push(path);
+                    }
+                }
+                Err(e) => {
+                    warn!("Error processing path: {:?}", e);
+                    self.iter.next(); // Skip the error
```
Comment (sebastiantia) [inline kernel/src/log_segment/delta_log_group_iterator.rs:78]: skipping `ParsedLogPath::try_from()` errors here as we were already filtering them out

File: kernel/src/log_segment.rs [hunk 2]
```diff
@@ -313,28 +312,33 @@ fn list_log_files_with_version(
...
-                    Ordering::Equal => checkpoint_parts.push(parsed_path),
-                    Ordering::Less => {}
-                },
+    let log_files = list_log_files(fs_client, log_root, start_version, end_version)?;
+
+    for (version, files) in &log_files
+        .filter_map(|res| match res {
+            Ok(path) => Some(path),
+            Err(e) => {
+                warn!("Error processing path: {:?}", e);
```
Comment (sebastiantia) [inline kernel/src/log_segment.rs:321]: skipping ParsedLogPath::try_from() errors here as we were already filtering them out

Comment (OussamaSaoudi-db) [reply kernel/src/log_segment.rs:321]: Hmm I think it's dangerous to skip the errors here. It's best to try to return the error somehow. Does it work if you do something like `chunk_by(|path| path.map(|x| x.version))`.

The proposed approach tries chunking by `DeltaResult<Version>` instead of chunking by `Version`. The hope is to return the `Err` if we encounter it.

File: kernel/src/log_segment.rs [hunk 3]
```diff
@@ -313,28 +312,33 @@ fn list_log_files_with_version(
...
+
+        for file in files {
+            if file.is_commit() {
+                commit_files.push(file);
+            } else if file.is_checkpoint() {
+                new_checkpoint_parts.push(file);
             }
         }
+        if validate_checkpoint_parts(version, &new_checkpoint_parts)
+            && (max_checkpoint_version.is_none() || Some(version) >= max_checkpoint_version)
```
Comment (OussamaSaoudi-db) [inline kernel/src/log_segment.rs:337]: I wonder if we can just validate. iirc the listing _should_ be in order. So the latest checkpoint should always be greater.

File: kernel/src/log_segment.rs [hunk 4]
```diff
@@ -377,3 +381,39 @@ fn list_log_files_with_checkpoint(
...
+/// Validates that all the checkpoint parts belong to the same checkpoint version and that all parts
+/// are present. Returns `true` if we have a complete checkpoint, `false` otherwise.
+fn validate_checkpoint_parts(version: u64, checkpoint_parts: &[ParsedLogPath]) -> bool {
+    if checkpoint_parts.is_empty() {
+        return false;
+    }
+
+    match checkpoint_parts.last().map(|file| &file.file_type) {
+        Some(LogPathFileType::MultiPartCheckpoint { num_parts, .. }) => {
+            if *num_parts as usize != checkpoint_parts.len() {
```
Comment (OussamaSaoudi-db) [inline kernel/src/log_segment.rs:394]: I  think it may be worth checking that:
1) all the checkpoint parts are indeed of type `MultiPartCheckpoint`
2) that the set of multi-part checkpoints has parts `0..n`.

@zachschuermann  what do you think?

File: kernel/src/log_segment.rs [hunk 5]
```diff
@@ -377,3 +381,39 @@ fn list_log_files_with_checkpoint(
...
+                warn!(
+                    "Found a single-part checkpoint at version {}. Found {} parts",
+                    version,
+                    checkpoint_parts.len()
+                );
+                return false;
+            }
+        }
+        // TODO: Include UuidCheckpoint once we actually support v2 checkpoints
+        _ => {}
```
Comment (OussamaSaoudi-db) [inline kernel/src/log_segment.rs:415]: I think uuidcheckpoint should return false, since we can't read that checkpoint. In general, beware catchall cases in match statements 

I also wonder if we should panic/error if we ever get a commit file here, since that *should not* be happening.

File: kernel/src/log_segment.rs (hunk 2 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:321]: The `chunk_by` function requires that the keys it uses for grouping implement the `PartialEq` trait so it can compare them, but the `Error` in the `DeltaResult` does not implement the trait so it doesn't work...

Comment (sebastiantia) [reply kernel/src/log_segment.rs:321]: We could use `try_collect` to handle errors _before_ grouping.
```
let log_files = list_log_files(fs_client, log_root, start_version, end_version)?;

let log_files: Vec<ParsedLogPath> = log_files.try_collect()?;

for (version, files) in &log_files.into_iter().chunk_by(|path| path.version)
```

File: kernel/src/log_segment.rs (hunk 5 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:415]: Right, good catch. I think returning an Error in the catchall case would be a good idea as we really should not get anything other than  `LogPathFileType::SinglePartCheckpoint` or `LogPathFileType::MultiPartCheckpoint` here.

File: kernel/src/log_segment.rs (hunk 3 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:337]: Hmm right, looks like we were assuming that to begin with as we returned commit files in the order given from `list_log_files`, and soon after required that they are ascending in version # [here](https://github.com/delta-io/delta-kernel-rs/blob/350d5b26cfa24b3e8f27355259724ebe7836f100/kernel/src/log_segment.rs#L53)...

Comment (sebastiantia) [reply kernel/src/log_segment.rs:337]: This gets rid of `max_checkpoint_version` entirely :)

File: kernel/src/log_segment.rs (hunk 2 above)
Comment (OussamaSaoudi) [reply kernel/src/log_segment.rs:321]: This was rly tricky and I got majorly nerdsniped thinking about the iterator stuff. But look into [process_result](https://docs.rs/itertools/latest/itertools/fn.process_results.html). 

I think I might've adapted your code right, but double check:
```rust
    let mut checkpoint_parts = vec![];
    let mut max_checkpoint_version = start_version;
    let mut commit_files = Vec::with_capacity(10);
    process_results(log_files, |iter| {
        let log_files = iter.chunk_by(move |x| x.version);

        for (version, files) in &log_files {
            let mut new_checkpoint_parts = vec![];

            for file in files {
                if file.is_commit() {
                    commit_files.push(file);
                } else if file.is_checkpoint() {
                    new_checkpoint_parts.push(file);
                }
            }
            if validate_checkpoint_parts(version, &new_checkpoint_parts) {
                max_checkpoint_version = Some(version);
                checkpoint_parts = new_checkpoint_parts;
            }
        }
    })?;
    Ok((commit_files, checkpoint_parts))

```

File: kernel/src/log_segment.rs (hunk 5 above)
Comment (OussamaSaoudi) [reply kernel/src/log_segment.rs:415]: I'd say handle the Uuid case separately from the catchall. Leave a comment that says this case will be supported in CheckpointV2.

Comment (scovich) [reply kernel/src/log_segment.rs:415]: +10 avoid catchall in match statements. Better to enumerate the known-invalid cases, so that when a new case shows up the compiler forces us to categorize it.

File: kernel/src/log_segment.rs (hunk 2 above)
Comment (hntd187) [reply kernel/src/log_segment.rs:321]: Generally the compiler will optimize better with `chunks_exact` than `chunks` it should be a drop in replacement.

Comment (hntd187) [reply kernel/src/log_segment.rs:321]: I would use try collect and propagate the errors.

Comment (sebastiantia) [reply kernel/src/log_segment.rs:321]: nice find with`process_results`, it works nicely!

**Review by scovich — COMMENTED** [review]
Flushing comments (possibly stale -- a newer version was pushed during review)

File: kernel/src/log_segment.rs (hunk 4 above)
Comment (OussamaSaoudi) [reply kernel/src/log_segment.rs:379]: this reminds me to use match statements to their full power in the future. Thx for the example Ryan!

**Comment by sebastiantia** [comment]
> Flushing comments (possibly stale -- a newer version was pushed during review)

Thanks for this!

File: kernel/src/log_segment.rs (hunk 4 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:379]: ah yes, did not consider the multiple incomplete checkpoints. I'll introduce tests to cover some of these scenarios. And thanks a lot for the example!

File: kernel/src/log_segment.rs (hunk 2 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs]: clearing the commit files when encountering complete checkpoints makes sense, and thank you for the helpful context @scovich, I'll go ahead and only return commit files _after_ the latest checkpoint

File: kernel/src/log_segment.rs [hunk 6]
```diff
@@ -377,3 +417,56 @@ fn list_log_files_with_checkpoint(
...
+            );
+            return false;
+        }
+        Some(LogPathFileType::Unknown) => {
+            warn!(
+                "Found an unknown file type at version {} when expecting a checkpoint",
+                version
+            );
+            return false;
+        }
```
Comment (OussamaSaoudi) [inline kernel/src/log_segment.rs:466]: This should never happen, and would imply that `is_checkpoint` is incorrect. Is this panic-worthy?

File: kernel/src/log_segment.rs [hunk 7]
```diff
@@ -377,3 +417,56 @@ fn list_log_files_with_checkpoint(
...
+                    "Found a multi-part checkpoint at version {}. Found {} parts, expected {}",
+                    version,
+                    checkpoint_parts.len(),
+                    num_parts
+                );
+                return false;
+            }
+        }
+        Some(LogPathFileType::SinglePartCheckpoint) => {
+            if checkpoint_parts.len() != 1 {
```
Comment (OussamaSaoudi) [inline kernel/src/log_segment.rs:437]: I'm wondering in what case this would happen?

File: kernel/src/log_segment.rs [hunk 8]
```diff
@@ -377,3 +417,56 @@ fn list_log_files_with_checkpoint(
     }
     Ok((commit_files, checkpoint_parts))
 }
+
+/// Validates that all the checkpoint parts belong to the same checkpoint version and that all parts
+/// are present. Returns `true` if we have a complete checkpoint, `false` otherwise.
+fn validate_checkpoint_parts(version: u64, checkpoint_parts: &[ParsedLogPath]) -> bool {
+    match checkpoint_parts.last().map(|file| &file.file_type) {
+        Some(LogPathFileType::MultiPartCheckpoint { num_parts, .. }) => {
+            if *num_parts as usize != checkpoint_parts.len() {
```
Comment (OussamaSaoudi) [inline kernel/src/log_segment.rs:426]: I wonder if we should match on (FileType, numparts), since we're checking the num parts in a lot of the cases.

File: kernel/src/log_segment.rs [hunk 9]
```diff
@@ -311,31 +311,71 @@ fn list_log_files_with_version(
...
+                        // Start a new multi-part checkpoint with at least 2 parts
+                        checkpoints.insert(*num_parts, vec![part_file]);
+                    }
+                    MultiPartCheckpoint {
+                        part_num,
+                        num_parts,
+                    } => {
+                        // Continue a new multi-part checkpoint with at least 2 parts
+                        if let Some(part_files) = checkpoints.get_mut(num_parts) {
+                            if *part_num == 1 + part_files.len() as u32 {
```
Comment (scovich) [inline kernel/src/log_segment.rs:356]: Widening conversions are safer:
```suggestion
                            if *part_num as usize == 1 + part_files.len() {
```
(again below)

File: kernel/src/log_segment.rs [hunk 10]
```diff
@@ -311,31 +311,71 @@ fn list_log_files_with_version(
...
-        } else if parsed_path.is_checkpoint() {
-            let path_version = parsed_path.version;
-            match max_checkpoint_version {
-                None => {
-                    checkpoint_parts.push(parsed_path);
-                    max_checkpoint_version = Some(path_version);
+    let log_files = list_log_files(fs_client, log_root, start_version, end_version)?;
+
+    process_results(log_files, |iter| {
+        let log_files = iter.chunk_by(move |x| x.version);
```
Comment (scovich) [inline kernel/src/log_segment.rs:318]: Why is the `move` needed here? The closure doesn't seem to capture any state?

File: kernel/src/log_segment.rs [hunk 11]
```diff
@@ -311,31 +311,71 @@ fn list_log_files_with_version(
...
+            // Find a complete checkpoint (all parts exist)
+            if let Some((_, complete_checkpoint)) = checkpoints
+                .into_iter()
+                .find(|(num_parts, part_files)| part_files.len() as u32 == *num_parts)
+            {
+                // Validate the checkpoint before updating state
+                if validate_checkpoint_parts(version, &complete_checkpoint) {
+                    checkpoint_parts = complete_checkpoint;
+                    commit_files.clear(); // Clear commit files once checkpoint is found
+                }
```
[the remark this answers is not in the document]
Comment (scovich) [reply kernel/src/log_segment.rs:375]: +1 for helper function, good idea. Based on Rule of 30, you might even consider pulling out a sub-helper to do the grouping on behalf of the helper

File: kernel/src/log_segment.rs [hunk 12]
```diff
@@ -311,31 +311,71 @@ fn list_log_files_with_version(
...
+                                // Safe to append because all previous parts exist
+                                part_files.push(part_file);
+                            }
+                        }
+                    }
+                    Commit | CompactedCommit { .. } | Unknown => {} // invalid file type => do nothing
+                }
+            }
+
+            // Find a complete checkpoint (all parts exist)
```
Comment (scovich) [inline kernel/src/log_segment.rs:366]: The code already makes it obvious _what_ we're doing ("find"). Maybe the comment (or doc comment for the helper) can explain _why_ -- we are looking for exactly _one_ complete checkpoint, no matter how many might exist for this version.

File: kernel/src/log_segment.rs [hunk 13]
```diff
@@ -311,31 +311,71 @@ fn list_log_files_with_version(
...
+            if let Some((_, complete_checkpoint)) = checkpoints
+                .into_iter()
+                .find(|(num_parts, part_files)| part_files.len() as u32 == *num_parts)
+            {
+                // Validate the checkpoint before updating state
+                if validate_checkpoint_parts(version, &complete_checkpoint) {
```
Comment (scovich) [inline kernel/src/log_segment.rs:372]: The code above already did this validation "in line" while populating the hashmap:
* The iterator chunking ensures that all parts come from the same commit version
* The hash table (keyed by num_parts) ensures that all parts in a given Vec come from the same multi-part checkpoint
* The length checking in the "continue" case ensures the sequence of parts is gap-free
  * This check is redundant, because the `ParsedLogPath` constructor already ensures that `(1..=num_parts).contains(part_num)`. There's no way to get a seemingly-complete incomplete checkpoint by wrongly numbered parts.
  * The check also eliminates any duplicates, but duplicates shouldn't be possible if this is actually a listing result.
  * The check also verifies order, but that doesn't actually matter (all checkpoint parts are independent of each other)
* The `find` ignores any incomplete checkpoint (any missing part would make the vec smaller than `num_parts`)

File: kernel/src/log_segment.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (scovich) [reply kernel/src/log_segment.rs:375]: Update: Based on all the other suggestions, I would recommend just one helper, to build the hashmap:
```rust
/// Groups all checkpoint parts according to the size of the checkpoint they belong to. 
///
/// NOTE: There could be a single-part and/or any number of uuid-based checkpoints. They
/// are all equivalent, and this routine keeps only one of them (arbitrarily chosen).
fn group_checkpoint_parts(parts: &[ParsedLogPath]) -> HashMap<u32, Vec<ParsedLogPath>>
```

File: kernel/src/log_segment.rs [hunk 14]
```diff
@@ -377,3 +417,56 @@ fn list_log_files_with_checkpoint(
...
 }
+
+/// Validates that all the checkpoint parts belong to the same checkpoint version and that all parts
+/// are present. Returns `true` if we have a complete checkpoint, `false` otherwise.
+fn validate_checkpoint_parts(version: u64, checkpoint_parts: &[ParsedLogPath]) -> bool {
+    match checkpoint_parts.last().map(|file| &file.file_type) {
+        Some(LogPathFileType::MultiPartCheckpoint { num_parts, .. }) => {
+            if *num_parts as usize != checkpoint_parts.len() {
+                warn!(
+                    "Found a multi-part checkpoint at version {}. Found {} parts, expected {}",
```
Comment (scovich) [inline kernel/src/log_segment.rs:428]: Note: This would imply either duplicates or part numbers outside the checkpoint's part range. The former should be impossible for a correct listing, and the latter would produce an error in [ParsedLogPath::try_from](https://github.com/delta-io/delta-kernel-rs/blob/main/kernel/src/path.rs#L135-L138).

File: kernel/src/log_segment.rs (hunk 6 above)
Comment (scovich) [reply kernel/src/log_segment.rs:466]: I thought about that as well, but panics are exceptionally unfriendly to whatever engine embeds kernel.
At some point we have to rely on correctness of `is_checkpoint`?

File: kernel/src/log_segment.rs (hunk 14 above)
Comment (zachschuermann) [reply kernel/src/log_segment.rs:428]: Hm considering we have this place and some below, I wonder if we should modify semantics such that the function returns a `Result<bool>` and we could leverage result to return `Error::internal` for some unexpected cases?

File: kernel/src/log_segment.rs (hunk 10 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:318]: You're right, no need for the `move` thanks for the catch :)

File: kernel/src/log_segment.rs (hunk 9 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:356]: nice catch!

File: kernel/src/log_segment.rs [hunk 15]
```diff
@@ -311,31 +311,71 @@ fn list_log_files_with_version(
...
+                .into_iter()
+                .find(|(num_parts, part_files)| part_files.len() as u32 == *num_parts)
+            {
+                // Validate the checkpoint before updating state
+                if validate_checkpoint_parts(version, &complete_checkpoint) {
+                    checkpoint_parts = complete_checkpoint;
+                    commit_files.clear(); // Clear commit files once checkpoint is found
+                }
             }
         }
```
[the remark this answers is not in the document]
Comment (sebastiantia) [reply kernel/src/log_segment.rs:377]: Ah nice find, I'll go ahead with this refactor

File: kernel/src/log_segment.rs (hunk 13 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:372]: Thanks for the breakdown, most of the validation in `validate_checkpoint_parts` is redundant due to the in-line validation you mentioned. For the sake of caution, I would still like to warn the user when encountering scenarios covered currently in the `validate_checkpoint_parts` function.
To do this, I've sprinkled in logging for scenarios below when grouping the checkpoints:
- unsupported UUID checkpoints
- invalid file types (commit, compacted, unknown)
- multiple single-part checkpoints

In `group_checkpoint_parts`, when we encounter a multi-part checkpoint which has arrived out of order, we do not try to build a complete checkpoint with it (we do not add it to our hashmap) as we assume that the parts should arrive in order. Thus we are _maybe_ left with an incomplete checkpoint part, as we could still find the remaining sequence of checkpoint parts in our iteration. I've added logging here for encountering an unexpected part number when grouping. We could additionally/alternatively do a second pass after grouping to find & warn for incomplete checkpoint parts as I remembered this was particularly important for this issue in general @OussamaSaoudi

File: kernel/src/log_segment.rs (hunk 14 above)
Comment (scovich) [reply kernel/src/log_segment.rs:428]: (maybe, but the whole function shouldn't even exist -- see other comment)

File: kernel/src/log_segment.rs (hunk 13 above)
Comment (scovich) [reply kernel/src/log_segment.rs:372]: > I've sprinkled in logging for scenarios below when grouping the checkpoints:
>
> *  unsupported UUID checkpoints
> *   invalid file types (commit, compacted, unknown)
> *    multiple single-part checkpoints

Re invalid file types and UUID checkpoints -- the `is_checkpoint` filter before this code should have already removed those. So any logging about UUID checkpoints would need to happen before that filtering, not here, which makes me question the utility of logging here for users' sake. The checks here are only really needed because rustc demands complete matches and it doesn't grok the concept that some cases could be statically impossible.

Meanwhile, why would multiple single-part checkpoints be a problem? The spec allows one classic checkpoint, one multi-part checkpoint with a single part, and any number of uuid checkpoints (tho the latter should be filtered out long before now). Any of them should be equivalent.

Comment (sebastiantia) [reply kernel/src/log_segment.rs:372]: Yea the logging would only reveal errors if `.is_checkpoint` did not behave correctly. Will summarize bullet points 1 & 2 with a single warn if file type is neither commit in the filtering you mentioned.

I see, the spec indeed allows for single-part checkpoints and we are correctly handling multiple single-part checkpoints as well. Thanks for the heads-up.

File: kernel/src/log_segment.rs (hunk 14 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs]: Right, @scovich pointed out that much of the logging here is redundant. I've summarized most to a single log when encountering an unknown file type when filtering the batched `log_files`. ref to discussion https://github.com/delta-io/delta-kernel-rs/pull/641#discussion_r1918409205

File: kernel/src/log_segment.rs (hunk 12 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs]: Updated 👍

File: kernel/src/log_segment.rs (hunk 13 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs]: @zachschuermann curious as to your thoughts about doing an additional pass after grouping the multi-part checkpoints to find an **incomplete** multi-part checkpoint for the purpose of warning the user.

File: kernel/src/log_segment.rs [hunk 16]
```diff
@@ -309,75 +309,84 @@ fn list_log_files_with_version(
...
-                .find(|(num_parts, part_files)| part_files.len() as u32 == *num_parts)
+                .find(|(num_parts, part_files)| part_files.len() == *num_parts as usize)
             {
-                // Validate the checkpoint before updating state
-                if validate_checkpoint_parts(version, &complete_checkpoint) {
-                    checkpoint_parts = complete_checkpoint;
-                    commit_files.clear(); // Clear commit files once checkpoint is found
-                }
+                checkpoint_parts = complete_checkpoint;
+                commit_files.clear(); // Clear commits when a complete checkpoint is found
```
Comment (scovich) [inline kernel/src/log_segment.rs:342]: Again, better to doc "why" rather than "what"
```suggestion
                commit_files.clear(); // Log replay only needs commits after a complete checkpoint
```

**Review by scovich — APPROVED** [review]
Approach looks good. Didn't dig deeply into unit tests.

File: kernel/src/log_segment/tests.rs [hunk 17]
```diff
@@ -107,6 +107,73 @@ fn build_log_with_paths_and_checkpoint(
...
+            // Part 2 is missing!
+            delta_path_for_multipart_checkpoint(3, 3, 3),
+            delta_path_for_multipart_checkpoint(3, 1, 4),
+            delta_path_for_multipart_checkpoint(3, 2, 4),
+            delta_path_for_multipart_checkpoint(3, 3, 4),
+            delta_path_for_multipart_checkpoint(3, 4, 4),
+            delta_path_for_version(4, "json"),
+            delta_path_for_version(5, "json"),
+            delta_path_for_version(6, "json"),
+            delta_path_for_version(7, "json"),
```
Comment (OussamaSaoudi) [inline kernel/src/log_segment/tests.rs:160]:
```suggestion
            delta_path_for_version(0, "json"),
            delta_path_for_multipart_checkpoint(1, 1, 3),
            // Part 2 of 3 at version 1 is missing!
            delta_path_for_multipart_checkpoint(1, 3, 3),
            delta_path_for_multipart_checkpoint(2, 1, 2),
            // Part  2 of 2 at version 2 is missing! 
            delta_path_for_version(2, "json"),
            delta_path_for_multipart_checkpoint(3, 1, 3),
            // Part 2 of 3 at version 3 is missing!
            delta_path_for_multipart_checkpoint(3, 3, 3),
            delta_path_for_multipart_checkpoint(3, 1, 4),
            delta_path_for_multipart_checkpoint(3, 2, 4),
            delta_path_for_multipart_checkpoint(3, 3, 4),
            delta_path_for_multipart_checkpoint(3, 4, 4),
            delta_path_for_version(4, "json"),
            delta_path_for_version(5, "json"),
            delta_path_for_version(6, "json"),
            delta_path_for_version(7, "json"),
```

File: kernel/src/log_segment/tests.rs [hunk 18]
```diff
@@ -296,6 +360,51 @@ fn build_snapshot_with_missing_checkpoint_part_no_hint() {
...
+
+    let (client, log_root) = build_log_with_paths_and_checkpoint(
+        &[
+            delta_path_for_version(0, "json"),
+            delta_path_for_version(1, "checkpoint.parquet"),
+            delta_path_for_version(2, "json"),
+            delta_path_for_version(3, "checkpoint.parquet"),
+            delta_path_for_version(4, "json"),
+            delta_path_for_multipart_checkpoint(5, 1, 3),
+            // Part 2 is missing!
```
Comment (OussamaSaoudi) [inline kernel/src/log_segment/tests.rs:386]:
```suggestion
            // Part 2 of 3 at version 5 is missing!
```

**Review by OussamaSaoudi — COMMENTED** [review]
Got a little confused with the test, so I added more detail to the comments. Looks good besides that!

File: kernel/src/log_segment/tests.rs (hunk 18 above)
Comment (OussamaSaoudi) [reply kernel/src/log_segment/tests.rs:386]: Do the same for `build_snapshot_with_missing_checkpoint_part_no_hint` for consistency

File: kernel/src/log_segment/tests.rs [hunk 19]
```diff
@@ -107,6 +107,73 @@ fn build_log_with_paths_and_checkpoint(
...
+}
+
+#[test]
+fn build_snapshot_with_multiple_incomplete_multipart_checkpoints() {
+    let (client, log_root) = build_log_with_paths_and_checkpoint(
+        &[
+            delta_path_for_version(0, "json"),
+            delta_path_for_multipart_checkpoint(1, 1, 3),
+            // Part 2 of 3 at version 1 is missing!
+            delta_path_for_multipart_checkpoint(3, 3, 3),
```
[the remark this answers is not in the document]
Comment (sebastiantia) [reply kernel/src/log_segment/tests.rs:146]: Agh, thanks for the catch!

**Review by OussamaSaoudi — APPROVED** [review]
good job!

File: kernel/src/log_segment.rs [hunk 20]
```diff
@@ -309,35 +309,84 @@ fn list_log_files_with_version(
...
-                None => {
-                    checkpoint_parts.push(parsed_path);
-                    max_checkpoint_version = Some(path_version);
+    let log_files = list_log_files(fs_client, log_root, start_version, end_version)?;
+
+    process_results(log_files, |iter| {
+        let mut commit_files = Vec::with_capacity(10);
+        let mut checkpoint_parts = vec![];
+
+        let log_files = iter.chunk_by(|x| x.version);
```
Comment (zachschuermann) [inline kernel/src/log_segment.rs:319]: nit: maybe rename and/or comment
```suggestion
        // get log files for each version
        let log_files_per_version = iter.chunk_by(|x| x.version);
```

File: kernel/src/log_segment.rs [hunk 21]
```diff
@@ -309,35 +309,84 @@ fn list_log_files_with_version(
...
-                        max_checkpoint_version = Some(path_version);
-                        checkpoint_parts.clear();
-                        checkpoint_parts.push(parsed_path);
+            }
+
+            // Group and find the first complete checkpoint for this version.
+            // All checkpoints for the same version are equivalent, so we only take one.
+            if let Some((_, complete_checkpoint)) = group_checkpoint_parts(new_checkpoint_parts)
+                .into_iter()
+                .find(|(num_parts, part_files)| part_files.len() == *num_parts as usize)
```
Comment (zachschuermann) [inline kernel/src/log_segment.rs:339]: use `TryFrom` or comment on safety of the cast

File: kernel/src/log_segment.rs [hunk 22]
```diff
@@ -309,35 +309,84 @@ fn list_log_files_with_version(
...
+                // Start a new multi-part checkpoint with at least 2 parts
+                checkpoints.insert(*num_parts, vec![part_file]);
+            }
+            MultiPartCheckpoint {
+                part_num,
+                num_parts,
+            } => {
+                // Continue a new multi-part checkpoint with at least 2 parts
+                if let Some(part_files) = checkpoints.get_mut(num_parts) {
+                    if *part_num as usize == 1 + part_files.len() {
```
Comment (zachschuermann) [inline kernel/src/log_segment.rs:380]: does this work? does this require checkpoints in order?

File: kernel/src/log_segment/tests.rs [hunk 23]
```diff
@@ -107,6 +107,73 @@ fn build_log_with_paths_and_checkpoint(
...
+    assert_eq!(checkpoint_parts.len(), 1);
+    assert_eq!(checkpoint_parts[0].version, 3);
+
+    let versions = commit_files.into_iter().map(|x| x.version).collect_vec();
+    let expected_versions = vec![4, 5, 6, 7];
+    assert_eq!(versions, expected_versions);
+}
+
+#[test]
+fn build_snapshot_with_multiple_incomplete_multipart_checkpoints() {
```
Comment (zachschuermann) [inline kernel/src/log_segment/tests.rs:140]: haven't looked much at the `build_log_with_paths_and_checkpoint` but assuming this is ordered, can we do some out-of-order tests?

File: kernel/src/log_segment.rs [hunk 24]
```diff
@@ -309,35 +309,84 @@ fn list_log_files_with_version(
...
+            {
+                checkpoint_parts = complete_checkpoint;
+                commit_files.clear(); // Log replay only uses commits after a complete checkpoint
+            }
+        }
+        (commit_files, checkpoint_parts)
+    })
+}
+
+/// Groups all checkpoint parts according to the size of the checkpoint they belong to.
```
Comment (zachschuermann) [inline kernel/src/log_segment.rs:349]:
```suggestion
/// Groups all checkpoint parts according to the the checkpoint they belong to.
```

**Review by zachschuermann — COMMENTED** [review]
left a few questions!

File: kernel/src/log_segment.rs (hunk 22 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:380]: Yes, this requires multi-part checkpoints to be in order. This should always be the case if log listing always returns files in a sorted fashion but testing this would be good

for ref https://github.com/delta-io/delta-kernel-rs/pull/641#discussion_r1918409205

Comment (scovich) [reply kernel/src/log_segment.rs:380]: re order: If listing wasn't in order, then the whole `chunk_by` approach would be broken from the start. And searching for the latest checkpoint would be super expensive because `_last_checkpoint` hint would be useless.

File: kernel/src/log_segment/tests.rs (hunk 23 above)
Comment (sebastiantia) [reply kernel/src/log_segment/tests.rs:140]: https://github.com/delta-io/delta-kernel-rs/pull/641#discussion_r1924442424 we rely on checkpoints to be listed in order from log listing.

File: kernel/src/log_segment.rs (hunk 22 above)
Comment (sebastiantia) [reply kernel/src/log_segment.rs:380]: A unit test for `list_log_files` would be good but will move forward with a comment documenting the dependency on sorted listing for now.

Comment (sebastiantia) [reply kernel/src/log_segment.rs:380]: Will leave a comment documenting dependency on sorted listing and move forward for now

File: kernel/src/log_segment.rs (hunk 13 above)
Comment (zachschuermann) [reply kernel/src/log_segment.rs]: looks like in the current form we don't? seems fine to me :)

File: kernel/src/log_segment.rs (hunk 22 above)
Comment (zachschuermann) [reply kernel/src/log_segment.rs]: ah yep thanks!

**Review by zachschuermann — APPROVED** [review]
lgtm

**Comment by zachschuermann** [comment]
`breaking-change` label seems incorrect?
