### PR TITLE
fix: drop partitionValues_parsed in build_remove_transform

### LINKED ISSUE #2426: Transaction::remove_files() fails with "Too few fields in output schema" when scan uses a partition-column predicate
### Describe the bug

## Summary                                                                                                                                                             
   
  `Transaction::remove_files(scan_metadata)` fails at commit time with `Generic delta kernel error: Too few fields in output schema` when the scan producing that        
  metadata used `ScanBuilder::with_predicate()` on a partition column. `build_remove_transform` 
  does not account for the `partitionValues_parsed` column that predicate-enabled scans emit alongside `stats_parsed`.
                                                                                                                                                                         
  ## Reproduction                                        

  Minimal standalone integration test — drop into `kernel/tests/repro.rs` and run with:                                                                                  
   
  ```                                                                                                                                                                    
  cargo test -p delta_kernel --test repro --all-features -- --nocapture
  ```                                                                                                                                                                    
   
  <details>                                                                                                                                                              
  <summary><code>repro.rs</code></summary>               
                                                                                                                                                                         
  ```rust
  use std::collections::HashMap;                                                                                                                                         
  use std::sync::Arc;                                    

  use delta_kernel::arrow::array::{ArrayRef, Int32Array, RecordBatch};
  use delta_kernel::arrow::datatypes::{                                                                                                                                  
      DataType as ArrowDataType, Field as ArrowField, Schema as ArrowSchema,                                                                                             
  };                                                                                                                                                                     
  use delta_kernel::committer::FileSystemCommitter;                                                                                                                      
  use delta_kernel::expressions::{Expression, Scalar};                                                                                                                   
  use delta_kernel::schema::{DataType, StructField, StructType};                                                                                                         
  use delta_kernel::transaction::create_table::create_table;                                                                                                             
  use delta_kernel::transaction::data_layout::DataLayout;                                                                                                                
  use delta_kernel::{FilteredEngineData, Snapshot};                                                                                                                      
  use test_utils::{test_table_setup_mt, write_batch_to_table};                                                                                                           
                                                                                                                                                                         
  #[tokio::test(flavor = "multi_thread", worker_threads = 2)]                                                                                                            
  async fn scan_with_partition_predicate_then_remove_files_fails() {                                                                                                     
      let (_tmp, path, engine) = test_table_setup_mt().expect("setup");                                                                                                  
      let schema = Arc::new(                                                                                                                                             
          StructType::try_new(vec![                                                                                                                                      
              StructField::nullable("id", DataType::INTEGER),                                                                                                            
              StructField::nullable("p0", DataType::BOOLEAN),                                                                                                            
          ])                                                                                                                                                             
          .expect("schema"),                                                                                                                                             
      );                                                                                                                                                                 
      let _ = create_table(&path, schema, "repro")       
          .with_data_layout(DataLayout::partitioned(vec!["p0".to_string()]))                                                                                             
          .build(engine.as_ref(), Box::new(FileSystemCommitter::new()))                                                                                                  
          .expect("build")                                                                                                                                               
          .commit(engine.as_ref())                                                                                                                                       
          .expect("commit create");                                                                                                                                      
                                                         
      let table_url = delta_kernel::try_parse_uri(&path).expect("uri");
      let snapshot: Arc<Snapshot> = Snapshot::builder_for(table_url)                                                                                                     
          .build(engine.as_ref())                                                                                                                                        
          .map(Arc::from)                                                                                                                                                
          .expect("snap");                                                                                                                                               
                                                         
      let data_schema = Arc::new(ArrowSchema::new(vec![ArrowField::new(                                                                                                  
          "id",                                                                                                                                                          
          ArrowDataType::Int32,
          true,                                                                                                                                                          
      )]));                                              
      let batch = RecordBatch::try_new(
          data_schema,                                                                                                                                                   
          vec![Arc::new(Int32Array::from(vec![1])) as ArrayRef],
      )                                                                                                                                                                  
      .expect("batch");                                  
      let mut pv = HashMap::new();                                                                                                                                       
      pv.insert("p0".to_string(), Scalar::Boolean(false));
      let snapshot = write_batch_to_table(&snapshot, engine.as_ref(), batch, pv)                                                                                         
          .await                                                                                                                                                         
          .expect("append");                                                                                                                                             
                                                                                                                                                                         
      let predicate =                                    
          Expression::column(["p0"]).eq(Expression::literal(Scalar::Boolean(false)));                                                                                    
      let scan = snapshot                                                                                                                                                
          .clone()                                                                                                                                                       
          .scan_builder()                                                                                                                                                
          .with_predicate(Arc::new(predicate))           
          .build()
          .expect("scan build");
                                                                                                                                                                         
      let mut chunks: Vec<FilteredEngineData> = Vec::new();
      for meta in scan.scan_metadata(engine.as_ref()).expect("scan_metadata") {                                                                                          
          let meta = meta.expect("meta");                                                                                                                                
          let (data, sv) = meta.scan_files.into_parts();
          let selected = if sv.is_empty() {                                                                                                                              
              data.len()                                                                                                                                                 
          } else {
              sv.iter().filter(|b| **b).count()                                                                                                                          
          };                                                                                                                                                             
          if selected == 0 {
              continue;                                                                                                                                                  
          }                                              
          chunks.push(FilteredEngineData::try_new(data, sv).expect("fed"));
      }                                                                                                                                                                  
      assert!(!chunks.is_empty(), "predicate should match the one live file");
                                                                                                                                                                         
      let mut txn = snapshot                             
          .clone()                                                                                                                                                       
          .transaction(Box::new(FileSystemCommitter::new()), engine.as_ref())
          .expect("txn")
          .with_operation("DELETE".to_string())
          .with_data_change(true);                                                                                                                                       
      for c in chunks {
          txn.remove_files(c);                                                                                                                                           
      }                                                  

      // PANICS HERE:
      //   Generic delta kernel error: Too few fields in output schema                                                                                                   
      //     at kernel/src/engine/arrow_expression/evaluate_expression.rs:172
      //     inside evaluate_transform_expression                                                                                                                        
      //     called from Transaction::generate_remove_actions                                                                                                            
      txn.commit(engine.as_ref()).expect("commit");                                                                                                                      
  }                                                                                                                                                                      
  ```                                                    
                                                                                                                                                                         
  </details>                                             

  Reproduces deterministically. Predicate column type (Int / Long / Bool), column-mapping mode (`none` / `name` / `id`), and partition column count (1 or 2) do not      
  change the outcome — any `with_predicate()` that references a partition column, followed by `remove_files()` on the resulting scan metadata, fails the same way on
  commit.                                                                                                                                                                
                                                         
  ## Root cause

  In `kernel/src/scan/log_replay.rs`, `scan_row_schema_with_parsed_columns` appends a `partitionValues_parsed` column to the scan output schema whenever the scan has an 
  active partition-touching predicate (i.e. `state_info.physical_partition_schema` is `Some(_)`). It appends `stats_parsed` analogously in the stats case.
                                                                                                                                                                         
  `Transaction::generate_remove_actions` in `kernel/src/transaction/mod.rs` picks its evaluator based on whether `stats_parsed` is present:                              
   
  ```rust                                                                                                                                                                
  let evaluator = if data.has_field(&stats_parsed_col) { 
      &stats_parsed_eval   // built with coalesce_stats_with_parsed = true
  } else {                                                                                                                                                               
      &base_eval            // built with coalesce_stats_with_parsed = false
  };                                                                                                                                                                     
  ```                                                    
                                                                                                                                                                         
  `build_remove_transform` drops `stats_parsed` when the coalesce path is taken, but **never drops `partitionValues_parsed`**. When the scan input carries that extra    
  field, the remove-transform iterates through it (no drop registered) and exhausts the target schema iterator, producing `Too few fields in output schema`.
                                                                                                                                                                         
  ## Proposed fix                                        

  Add an unconditional drop of `partitionValues_parsed` at the end of `build_remove_transform` in `kernel/src/transaction/mod.rs`:
                                                                                                                                                                         
  ```rust
  // Inside fn build_remove_transform, after the stats / tags handling and before                                                                                        
  // the deletionVector insertions:                                                                                                                                      
  transform = transform.with_dropped_field_if_exists("partitionValues_parsed");
  ```                                                                                                                                                                    
                                                         
  This is a no-op when the field is absent, so it is safe for non-predicate scans.                                                                                       
                                                         
  **Fix verified locally**: with this single line added, the repro passes, and 50 random scenarios from a fuzz generator that triggers this combination go green (they 
  fail at ~10% rate without the fix).                                                                                                                                    
   
  ## Suggested regression test                                                                                                                                           
                                                         
  There is no integration test in the kernel that combines `ScanBuilder::with_predicate()` with `Transaction::remove_files()`. I'd suggest a regression test in 
  `kernel/tests/write.rs` alongside the existing `test_remove_files_*` cases, essentially matching the repro above.                                                      
   
  ## Impact                                                                                                                                                              
                                                         
  Any connector that performs partition-scoped deletes by using predicate pushdown to find the affected files (a natural pattern: "delete the files in the partition I 
  want to drop") cannot use this path today.                                                                                                                             
   
  Workarounds exist — full scan + client-side filter by partition value, then `remove_files` — but they're less efficient and not the obvious API usage.                 
                                                         
  ## Discovered by
                                                                                                                                                                         
  Randomized cross-engine fuzz harness. The generator emitted `DeletePartition` ops which exercised this combination across partition types and column-mapping modes. 
  Failure rate was consistent and type-agnostic (10/100 random scenarios), which ruled out type-specific bugs and pointed at the predicate + remove pairing itself.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rliao147**
## What changes are proposed in this pull request?

Fixes #2426. `Transaction::remove_files` failed at commit with "Too few fields in output schema" when fed scan metadata produced by a scan that had a partition touching predicate. `Scan::with_predicate` on a partition column adds a `partitionValues_parsed` column to the scan output schema, and `build_remove_transform` had no drop rule for it. This fix adds the missing `.with_dropped_field_if_exists(PARTITION_VALUES_PARSED_FIELD)` to the remove transform.

## How was this change tested?
Added a test which creates a partitioned table, writes two partitions, runs a scan, feeds the scan metadata into `remove_files`, and asserts commit succeeds with exactly one remove action for the partition.

### CODE REVIEW

File: kernel/src/transaction/mod.rs [hunk 1]
```diff
@@ -1327,7 +1328,11 @@ fn build_remove_transform(
             Expression::column([FILE_CONSTANT_VALUES_NAME, DEFAULT_ROW_COMMIT_VERSION_NAME]).into(),
         )
         .with_dropped_field(FILE_CONSTANT_VALUES_NAME)
-        .with_dropped_field("modificationTime");
+        .with_dropped_field("modificationTime")
+        // Scans with a partition-touching predicate add `partitionValues_parsed`
+        // to the scan output schema (see scan/log_replay.rs); drop it so the
+        // remove-transform's field count matches its target schema. See #2426.
```
Comment (DrakeLin) [inline kernel/src/transaction/mod.rs]: let's drop the issue number from the code

File: kernel/src/transaction/mod.rs
Comment (DrakeLin) [inline kernel/src/transaction/mod.rs]: should we mention parsed partition values in the docs

File: kernel/tests/write.rs [hunk 2]
```diff
@@ -3116,6 +3116,103 @@ async fn test_remove_files_after_predicate_scan_includes_stats_parsed(
     Ok(())
 }
 
+/// Scan with a partition predicate -> `Transaction::remove_files` commits and produces
+/// remove actions only for the targeted partition.
+#[tokio::test]
+async fn test_remove_files_after_partition_predicate_scan() -> Result<(), Box<dyn std::error::Error>>
```
Comment (DrakeLin) [inline kernel/tests/write.rs]: can we add a test for both parsed partition values and parsed stats dropping? See surrounding tests

**Review by DrakeLin — APPROVED** [review]

File: kernel/src/transaction/mod.rs [hunk 3]
```diff
@@ -1327,7 +1328,11 @@ fn build_remove_transform(
             Expression::column([FILE_CONSTANT_VALUES_NAME, DEFAULT_ROW_COMMIT_VERSION_NAME]).into(),
         )
         .with_dropped_field(FILE_CONSTANT_VALUES_NAME)
-        .with_dropped_field("modificationTime");
+        .with_dropped_field("modificationTime")
```
Comment (emkornfield) [inline kernel/src/transaction/mod.rs:1334]: please see how stats_parsed is handled, I think we might need a coalesce someplace but I'm not sure.

**Review by Jameson-Crate — APPROVED** [review]
Looks good, did you ensure that there were already other tests in which there are partition values present, but not in the scan predicate, you have some remove actions and the behavior is still as expected?

File: kernel/src/transaction/mod.rs (hunk 1 above)
Comment (rliao147) [reply kernel/src/transaction/mod.rs]: Done

File: kernel/src/transaction/mod.rs
Comment (rliao147) [reply kernel/src/transaction/mod.rs]: Added

File: kernel/src/transaction/mod.rs (hunk 3 above)
Comment (rliao147) [reply kernel/src/transaction/mod.rs:1334]: Thanks for bringing this up. Unlike stats, no coalesce is needed because `fileConstantValues.partitionValues` is always populated.

File: kernel/tests/write.rs (hunk 2 above)
Comment (rliao147) [reply kernel/tests/write.rs]: done

**Review by rliao147 — COMMENTED** [review]
Added more test dimensions/cases in the latest commit
