### PR TITLE
fix: acceptance test framework should reject negative snapshot version

### LINKED ISSUE #2265: Disallow negative versions when constructing a snapshot
### Please describe why this is necessary.

Kernel currently allows constructing snapshots with invalid negative versions.

### Describe the functionality you are proposing.

Return an error if the version is invalid.

### Additional context

Once fixed, you should enable the test `dsReadVersionNegative/specs/dsReadVersionNegative_error` in `acceptance_workloads_reader.rs`

### PR DESCRIPTION
**Pull request by kyli87**
## What changes are proposed in this pull request?
Fixes https://github.com/delta-io/delta-kernel-rs/issues/2265.

The issue linked above originally assumed that the Rust kernel was incorrectly allowing negative snapshot versions. However upon inspection - this is not possible because we use `u64` as the Version type. It turns out that the acceptance test framework was silently casting negative versions from the test specs into u64.

**Proposed Fix**
- The acceptance test framework parses version as i64, but then errors out while trying to execute such test specs

**Rationale**
- In the spirit of "best possible Rust API", we shouldn't modify our existing snapshot construction logic to take in i64s (only to then error out at runtime). 
- Since DAT allows negative version numbers, we can instead rely on the test execution logic to error out on these cases and hence match the Err outcome expected by the test spec. 

## How was this change tested?
Removed the failing DAT workload from the allowlist of failures. Also added unit testing for the JSON parsing and version handling inside of the test framework.

### CODE REVIEW

File: benchmarks/src/models.rs [hunk 1]
```diff
@@ -170,17 +170,31 @@ pub enum DataLayout {
...
+        timestamp: String,
+    },
 }
 
 impl TimeTravel {
-    /// Returns the version if this is version-based time travel.
+    /// Returns the version if this is version-based time travel and the version is non-negative.
     ///
-    /// Returns an error message for timestamp-based time travel, which is not yet supported.
+    /// Returns an error for negative versions or for timestamp-based time travel( which is not
```
Comment (chiinlquah) [inline benchmarks/src/models.rs]: nit: weird formatting around (

File: benchmarks/src/models.rs [hunk 2]
```diff
@@ -170,17 +170,31 @@ pub enum DataLayout {
...
     pub fn as_version(&self) -> Result<u64, &'static str> {
         match self {
-            TimeTravel::Version { version } => Ok(*version),
+            TimeTravel::Version { version } => {
+                if *version < 0 {
+                    Err("Only non-negative snapshot versions are supported")
+                } else {
+                    Ok(*version as u64)
+                }
+            }
```
Comment (chiinlquah) [inline benchmarks/src/models.rs]: less LOC variant
```
TimeTravel::Version { version } => u64::try_from(*version).map_err(...)
```

File: benchmarks/src/models.rs [hunk 3]
```diff
@@ -170,17 +170,31 @@ pub enum DataLayout {
 #[derive(Clone, Debug, Deserialize)]
 #[serde(untagged)]
 pub enum TimeTravel {
-    Version { version: u64 },
-    Timestamp { timestamp: String },
+    /// Snapshot/read version from the workload JSON. It is i64 so that negative values from
+    /// the test spec can be deserialized correctly; We rely on [`TimeTravel::as_version`] to reject
```
Comment (chiinlquah) [inline benchmarks/src/models.rs]: let's take out the WE
```
[`TimeTravel::as_version`] rejects values below zero.
```

File: benchmarks/src/models.rs [hunk 4]
```diff
@@ -170,17 +170,31 @@ pub enum DataLayout {
...
+    /// values below zero.
+    Version {
+        version: i64,
+    },
+    Timestamp {
```
Comment (chiinlquah) [inline benchmarks/src/models.rs]: nit: let's also add a brief comment for Timestamp to make them consisitent?

**Review by chiinlquah — COMMENTED** [review]
Nice find!! thanks for the change!

**Review by chiinlquah — APPROVED** [review]
LGTM! Thanks

**Review by OussamaSaoudi — APPROVED** [review]
