### PR TITLE
fix!: LogSegment's checkpoint_schema from hint should only be used when valid

### LINKED ISSUE #2361: fix: LogSegment::checkpoint_schema doesn't respect snapshot version
### Describe the bug

During snapshot creation with a hint file, we populate the checkpoint_schema in LogSegment regardless of whether this snapshot is actually for a version that is greater than the version mentioned in the hint file. This could mean that we are using newer schema on an older snapshot. See discussion here: https://github.com/delta-io/delta-kernel-rs/pull/2328#discussion_r3042090738

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kyli87**
## What changes are proposed in this pull request?
Fixes https://github.com/delta-io/delta-kernel-rs/issues/2361. There is a bug where we may try to use checkpoint schema from the last_checkpoint hint file, even though that schema is from a checkpoint version that is outside of the version range for the current snapshot.

This PR fixes it by adding an explicit getter to LogSegment which will filter out the checkpoint_schema if it is for a version that does not match the LogSegment's checkpoint version. All access of checkpoint_schema must then go through this getter instead.

## How was this change tested?
Added a unit test that fails before the change (repro'ing the bug) and passes after.

### CODE REVIEW

File: kernel/src/log_segment.rs [hunk 1]
```diff
@@ -209,6 +215,32 @@ impl LogSegment {
...
+    }
+
+    /// Returns the checkpoint schema from the `_last_checkpoint` hint when it is safe to use for
+    /// this segment's checkpoint.
+    ///
+    /// Returns `None` if there is no hint, if the hint omitted `checkpointSchema`, or if the
+    /// hint's checkpoint version is greater than [`Self::end_version`].
+    pub(crate) fn checkpoint_schema(&self) -> Option<SchemaRef> {
+        let m = self.last_checkpoint_metadata.as_ref()?;
+        if m.version > self.end_version {
```
Comment (DrakeLin) [inline kernel/src/log_segment.rs]:
```suggestion
        if Some(m.version) != self.checkpoint_version {
```

I think last_checkpoint_version < end_version isn't strict enough either because it might be a previous checkpoint

**Review by DrakeLin — CHANGES_REQUESTED** [review]

File: kernel/src/log_segment.rs (hunk 1 above)
Comment (kyli87) [reply kernel/src/log_segment.rs]: Ah oops good point - fixed and parameterized tests to cover this case

**Review by DrakeLin — APPROVED** [review]

**Review by Jameson-Crate — APPROVED** [review]
