### PR TITLE
fix: Include domain metadata in checkpoints

### LINKED ISSUE #1716: bug: delta-kernel-rs doesn't write domain metadatas during checkpoint
## Summary

When creating a checkpoint, domain metadata actions are not written to the checkpoint file. This causes domain metadata to be lost when reading a snapshot that uses the checkpoint.

## Reproduction

The following test demonstrates the issue:

```rust
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn test_checkpoint_preserves_domain_metadata() -> DeltaResult<()> {
    // Create a temp directory for the table
    let tmp_dir = tempdir().unwrap();
    let table_path = tmp_dir.path();
    let table_url = Url::from_directory_path(table_path).unwrap();

    // Create _delta_log directory
    std::fs::create_dir_all(table_path.join("_delta_log")).unwrap();

    // Version 0: create table with protocol (v3/v7) and metadata supporting domainMetadata
    let commit0 = [
        json!({
            "protocol": {
                "minReaderVersion": 3,
                "minWriterVersion": 7,
                "readerFeatures": [],
                "writerFeatures": ["domainMetadata"]
            }
        }),
        json!({
            "metaData": {
                "id": "test-table-id",
                "format": { "provider": "parquet", "options": {} },
                "schemaString": "{\"type\":\"struct\",\"fields\":[{\"name\":\"value\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}}]}",
                "partitionColumns": [],
                "configuration": {},
                "createdTime": 1587968585495i64
            }
        }),
    ]
    .map(|j| j.to_string())
    .join("\n");
    std::fs::write(
        table_path.join("_delta_log/00000000000000000000.json"),
        commit0,
    )
    .unwrap();
    println!("Created table at version 0 with domainMetadata writer feature");

    let store = Arc::new(LocalFileSystem::new());
    let executor = Arc::new(TokioMultiThreadExecutor::new(
        tokio::runtime::Handle::current(),
    ));
    let engine = DefaultEngineBuilder::new(store.clone())
        .with_task_executor(executor)
        .build();

    // Version 1: add domain metadata foo=bar1 via transaction
    let snapshot = Snapshot::builder_for(table_url.clone()).build(&engine)?;
    println!("Loaded snapshot at version {}", snapshot.version());
    let txn = snapshot.transaction(Box::new(FileSystemCommitter::new()))?;
    println!("Started transaction");
    let result = txn
        .with_domain_metadata("foo".to_string(), "bar1".to_string())
        .commit(&engine)?;
    assert!(result.is_committed());
    println!("Committed domain metadata foo=bar1");

    // Version 2: add domain metadata foo=bar2 (overwrites bar1) via transaction
    let snapshot = Snapshot::builder_for(table_url.clone()).build(&engine)?;
    println!("Loaded snapshot at version {}", snapshot.version());
    let txn = snapshot.transaction(Box::new(FileSystemCommitter::new()))?;
    println!("Started transaction");
    let result = txn
        .with_domain_metadata("foo".to_string(), "bar2".to_string())
        .commit(&engine)?;
    assert!(result.is_committed());
    println!("Committed domain metadata foo=bar2 (overwrites bar1)");

    // Load snapshot at latest version and verify domain metadata
    let snapshot = Snapshot::builder_for(table_url.clone()).build(&engine)?;
    println!(
        "Re-loaded fresh snapshot at version {}. Checking domain metadata...",
        snapshot.version()
    );
    assert_eq!(snapshot.version(), 2);
    let domain_value = snapshot.get_domain_metadata("foo", &engine)?;
    println!("Domain 'foo' = {:?}", domain_value);
    assert_eq!(domain_value, Some("bar2".to_string()));
    println!("Verified domain 'foo' = 'bar2' before checkpoint");

    // Trigger checkpoint
    println!("Triggering checkpoint at version 2...");
    snapshot.checkpoint(&engine)?;
    println!("Checkpoint complete");

    // Re-load snapshot at version 2 and verify domain metadata is preserved
    println!("Re-loading snapshot after checkpoint...");
    let snapshot = Snapshot::builder_for(table_url)
        .at_version(2)
        .build(&engine)?;
    println!("Loaded snapshot at version {}", snapshot.version());
    let domain_value = snapshot.get_domain_metadata("foo", &engine)?;
    println!("Domain 'foo' = {:?}", domain_value);
    println!("We lost the domain metadata!");
    assert_eq!(domain_value, Some("bar2".to_string()));

    Ok(())
}
```

## Test Output

```
Created table at version 0 with domainMetadata writer feature
Loaded snapshot at version 0
Started transaction
Committed domain metadata foo=bar1
Loaded snapshot at version 1
Started transaction
Committed domain metadata foo=bar2 (overwrites bar1)
Re-loaded fresh snapshot at version 2. Checking domain metadata...
Domain 'foo' = Some("bar2")
Verified domain 'foo' = 'bar2' before checkpoint
Triggering checkpoint at version 2...
Checkpoint complete
Re-loading snapshot after checkpoint...
Loaded snapshot at version 2
Domain 'foo' = None
We lost the domain metadata!
```

## Expected Behavior

After checkpoint, `get_domain_metadata("foo")` should return `Some("bar2")`.

## Actual Behavior

After checkpoint, `get_domain_metadata("foo")` returns `None`. The domain metadata is lost because it is not written to the checkpoint file.

### PR DESCRIPTION
**Pull request by scottsand-db**
## 🥞 Stacked PR
Use this [link](https://github.com/delta-io/delta-kernel-rs/pull/1718/files) to review incremental changes.
- [**stack/checkpoint_domain_metadata_fix**](https://github.com/delta-io/delta-kernel-rs/pull/1718) [[Files changed](https://github.com/delta-io/delta-kernel-rs/pull/1718/files)]

---------
## What changes are proposed in this pull request?

Closes #1716

Domain metadata was not being written to checkpoint files, causing it to be lost when reading snapshots that use checkpoints.

### The Fix

1. Added `DomainMetadata` to `CHECKPOINT_ACTIONS_SCHEMA` so domain metadata actions are included when writing checkpoints
2. Added `domainMetadata.removed` column to `ActionReconciliationVisitor` to properly filter out tombstones (`removed=true`) per the protocol spec, which states checkpoints should contain "Live Domain Metadata actions at this version, **excluding tombstones**"

## How was this change tested?

- Added integration test `test_checkpoint_preserves_domain_metadata` that:
  1. Creates a table with domain metadata support
  2. Commits domain metadata twice (to verify deduplication works)
  3. Verifies domain metadata is readable before checkpoint
  4. Creates a checkpoint
  5. Verifies domain metadata is still readable after checkpoint
- All existing tests pass

### CODE REVIEW

File: kernel/src/checkpoint/tests.rs [hunk 1]
```diff
@@ -664,3 +667,82 @@ async fn test_snapshot_checkpoint() -> DeltaResult<()> {
...
+        let result = txn
+            .with_domain_metadata(domain.to_string(), value.to_string())
+            .commit(&engine)?;
+        assert!(result.is_committed());
+        Ok(())
+    };
+
+    // ===== Commit Domain Metadata =====
+    commit_domain_metadata("foo", "bar1")?;
+    commit_domain_metadata("foo", "bar2")?;
```
Comment (nicklan) [inline kernel/src/checkpoint/tests.rs:729]: do we have an easy way to add another domain that we then remove, and ensure that _doesn't_ end up in the post checkpoint snapshot?

**Review by nicklan — APPROVED** [review]
lgtm, just one suggestion for ensuring we don't keep removed domains.

thanks for the quick turnaround!

File: kernel/src/checkpoint/tests.rs (hunk 1 above)
Comment (scottsand-db) [reply kernel/src/checkpoint/tests.rs:729]: I was just adding the TODO as you commented that!

Yes -- hard to test that the checkpoint indeed does _not_ contain tombstoned domain metadatas

File: kernel/src/checkpoint/tests.rs [hunk 2]
```diff
@@ -664,3 +667,82 @@ async fn test_snapshot_checkpoint() -> DeltaResult<()> {
...
+#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
+async fn test_checkpoint_preserves_domain_metadata() -> DeltaResult<()> {
+    // ===== Setup =====
+    let tmp_dir = tempdir().unwrap();
+    let table_path = tmp_dir.path();
+    let table_url = Url::from_directory_path(table_path).unwrap();
+    std::fs::create_dir_all(table_path.join("_delta_log")).unwrap();
+
+    // ===== Create Table =====
+    let commit0 = [
```
Comment (scottsand-db) [inline kernel/src/checkpoint/tests.rs:680]: @sanujbasu -- I am looking forward to your create-table work!
