### PR TITLE
test: add CTAS integration tests with column naming verification

### LINKED ISSUE #1647: [Test] Add write integration tests to test CTAS and that we can't add remove/ update actions post create in the same transaction
### Describe the bug

 Create table transactions are guarded against having remove actions or DV updates.
The invariants are enforced in:
 generate_remove_actions(): returns Error::internal_error("CREATE TABLE transaction cannot have remove actions")
 generate_dv_update_actions(): returns Error::internal_error("CREATE TABLE transaction cannot have DV update actions")

 These guards only trigger when:
 1. is_create_table() returns true, AND
 2. There are actually files queued for removal/DV updates (!self.remove_files_metadata.is_empty() or !self.dv_matched_files.is_empty())
Testing these error paths requires setting up tables with actual data files, which is covered by the write integration tests. The create_table module focuses on verifying the basic create table flow succeeds without data modifications. We need to add write integration tests
for more comprehensive coverage.

### PR DESCRIPTION
**Pull request by sanujbasu**
Fixes #1647

## What changes are proposed in this pull request?
Add a new test module (kernel/tests/create_table/ctas.rs) that exercises a CTAS-style flow: create source table, write seed data, scan, create target table, write scanned data, then verify the target.

Column naming verification dispatches to focused sub-checks, each operating in logical (CM off) or physical (CM on) mode:
  - Schema annotations (delegates to shared assert_column_mapping_config)
  - Stats key naming (verify_column_names_in_stats)
  - Clustering domain metadata naming (verify_column_names_in_clustering_metadata)
  - Parquet footer field naming (verify_column_names_in_parquet_footer)

Test matrix covers all three column mapping modes (None/Name/Id):
  - test_ctas_column_mapping_combinations: 9 combinations of src/tgt column mapping mode (3x3, no clustering)
  - test_ctas_clustering_and_column_mapping_combinations: 27 additional clustering combinations (gated behind clustered-table feature, skips the 9 non-clustered cases already covered above)

## How was this change tested?
The PR introduces a new test battery which was executed.

### CODE REVIEW

File: kernel/tests/create_table/ctas.rs [hunk 1]
```diff
@@ -0,0 +1,421 @@
...
+    engine: &impl Engine,
+    cm_mode: ColumnMappingMode,
+) -> Result<(), Box<dyn std::error::Error>> {
+    let schema = snapshot.schema();
+    let add_actions = read_add_infos(snapshot, engine)?;
+    let stats = add_actions
+        .iter()
+        .filter_map(|a| a.stats.as_ref())
+        .find(|s| s.get("minValues").is_some());
+
```
Comment (dengsh12) [inline kernel/tests/create_table/ctas.rs:72]: Wonder if we want to assert `maxValues` as well?

File: kernel/tests/create_table/ctas.rs [hunk 2]
```diff
@@ -0,0 +1,421 @@
...
+        .expect("Clustering columns should be present");
+
+    assert_eq!(
+        clustering_columns.len(),
+        1,
+        "Expected exactly one clustering column"
+    );
+    let stored_path = clustering_columns[0].path();
+    let col = ColumnName::new(["row_number"]);
+    let expected = get_any_level_column_physical_name(schema.as_ref(), &col, cm_mode)?.into_inner();
```
Comment (dengsh12) [inline kernel/tests/create_table/ctas.rs:114]: Wonder if we want to hardcode the col. Maybe make it a para so that the helper is more general?

**Review by DrakeLin — APPROVED** [review]

File: kernel/tests/create_table/ctas.rs [hunk 3]
```diff
@@ -0,0 +1,421 @@
...
+/// table metadata surfaces: schema annotations, stats, clustering domain
+/// metadata, and Parquet file footers.
+async fn verify_column_names_in_metadata(
+    snapshot: &Snapshot,
+    engine: &impl Engine,
+    store: &dyn ObjectStore,
+    table_url: &Url,
+    cm_mode: ColumnMappingMode,
+    clustered: bool,
+) -> Result<(), Box<dyn std::error::Error>> {
```
Comment (DrakeLin) [inline kernel/tests/create_table/ctas.rs:49]: DeltaResult

File: kernel/tests/create_table/ctas.rs (hunk 1 above)
Comment (sanujbasu) [reply kernel/tests/create_table/ctas.rs:72]: Yes. This is very good callout. I have already added the suggested test extensions in a followup PR.

File: kernel/tests/create_table/ctas.rs (hunk 2 above)
Comment (sanujbasu) [reply kernel/tests/create_table/ctas.rs:114]: This is also addressed in a followup

File: kernel/tests/create_table/ctas.rs (hunk 3 above)
Comment (sanujbasu) [reply kernel/tests/create_table/ctas.rs:49]: verify_column_names_in_metadata and its callees use ? on multiple non-kernel error types (object_store, serde_json, std::io), so they can't return DeltaResult<()> without wrapping every error. Box<dyn std::error::Error> is the idiomatic choice for integration test helpers with mixed error types.
