### PR TITLE
fix: Handle predicates on non-nullable columns without stats

### LINKED ISSUE #698: "Encountered unmasked nulls" error parsing stats for a non-nullable partition column
### Describe the bug

This is related to this DuckDB-Delta issue: https://github.com/duckdb/duckdb-delta/issues/96

When querying a Delta table from DuckDB with a where clause on a non-nullable partition field, I get the following error from delta-kernel-rs:
```
Error: IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: '<table_path>'): Hit error: 2 (ArrowError) with message (Json error: whilst decoding field 'nullCount': Encountered unmasked nulls in non-nullable StructArray child: Field { name: "partition_col", data_type: Int64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }
   0: delta_kernel::error::Error::with_backtrace
   1: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   2: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   3: core::iter::adapters::try_process
   4: delta_kernel::engine::arrow_utils::parse_json
   5: <delta_kernel::engine::default::json::DefaultJsonHandler<E> as delta_kernel::JsonHandler>::parse_json
   6: delta_kernel::scan::data_skipping::DataSkippingFilter::apply
   7: delta_kernel::scan::log_replay::LogReplayScanner::process_scan_batch
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   9: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::try_fold
  10: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  11: kernel_scan_data_next
```

### To Reproduce

I'm not that familiar with delta-kernel-rs itself so don't have a repro that only uses delta-kernel-rs, but this demonstrates the problem using DuckDB from Python:

```python
import duckdb
from deltalake import write_deltalake
import pyarrow as pa


delta_dir = "./delta_table"

schema = pa.schema([
    pa.field("partition_col", pa.string(), nullable=False),
    pa.field("x", pa.float32(), nullable=True),
])

for partition_col in ["AB", "CD", "EF"]:
    num_rows = 1_000
    table = pa.Table.from_pydict({
        'partition_col': pa.array([partition_col] * num_rows, type=pa.string()),
        'x': pa.array([i / 100.0 for i in range(num_rows)], type=pa.float32()),
    })
    write_deltalake(
            table_or_uri=delta_dir,
            data=table,
            partition_by=["partition_col"],
            mode='append',
            schema=schema)

results = duckdb.query(f"SELECT * FROM delta_scan('{delta_dir}') WHERE partition_col = 'CD'")
```

Tested with deltalake v0.24.0, duckdb v1.2.0.

### Expected behavior

No error

### Additional context

The error happens because the nullability of the null count is derived from the nullability of the column, but because the column is a partition column, it has no entries in the statistics: https://github.com/delta-io/delta-kernel-rs/blob/e6aefda96a620ae4b4fb2752afc20e175322a392/kernel/src/scan/data_skipping.rs#L81-L83

I made a partial fix that gets past the error for `nullCount`:

```diff
--- a/kernel/src/scan/data_skipping.rs
+++ b/kernel/src/scan/data_skipping.rs
@@ -77,6 +77,22 @@ impl DataSkippingFilter {
             ) -> Option<Cow<'a, PrimitiveType>> {
                 Some(Cow::Owned(PrimitiveType::Long))
             }
+
+            fn transform_struct_field(&mut self, field: &'a StructField) -> Option<Cow<'a, StructField>> {
+                // Change any struct fields to be nullable, as eg. a non-nullable field
+                // used for partitioning won't have any null counts
+                use Cow::*;
+                let field = match self.transform(&field.data_type)? {
+                    Borrowed(_) => Borrowed(field),
+                    Owned(new_data_type) => Owned(StructField {
+                        name: field.name.clone(),
+                        data_type: new_data_type,
+                        nullable: true,
+                        metadata: field.metadata.clone(),
+                    }),
+                };
+                Some(field)
+            }
         }
         let nullcount_schema = NullCountStatsTransform
             .transform_struct(&referenced_schema)?
```

But then I get the same error for the `minValues` field an I'm not sure how best to handle that, as we probably only want to treat partition columns as nullable. And this feels a bit like treating the symptom rather than the cause; delta-kernel-rs doesn't really need to parse stats at all if filtering on a partition column.

### PR DESCRIPTION
**Pull request by adamreeve**
Fixes #698

## What changes are proposed in this pull request?

Updates the `DataSkippingFilter` to treat all columns as nullable for the purpose of parsing stats, as suggested in https://github.com/delta-io/delta-kernel-rs/issues/698#issuecomment-2658229733.

This is particularly important for partition columns, which won't have values present in stats. But stats are also only usually stored for the first 32 columns, so we shouldn't rely on stats being present for non-partition fields either.

## How was this change tested?

I've added a new unit test.

I've also tested building duckdb-delta with this change (cherry-picked onto 0.6.1) and verified that the code in #698 now works.

### CODE REVIEW

**Comment by adamreeve** [comment]
> But stats are also only usually stored for the first 32 columns, so we shouldn't rely on stats being present for non-partition fields either.

I haven't added a separate test for this, but I verified this is also a problem with DuckDB-Delta. The following code also crashes without this fix:
```python
import duckdb
from deltalake import write_deltalake
import pyarrow as pa
import numpy as np


delta_dir = "./delta_table"
num_cols = 33

schema = pa.schema([
    pa.field(f"x{i}", pa.int32(), nullable=False) for i in range(num_cols)
])

rng = np.random.default_rng(0)
for p in range(10):
    num_rows = 1_000
    table = pa.Table.from_pydict({
        f'x{i}': pa.array(rng.integers(p * 100, (p + 1) * 100, num_rows), type=pa.int32()) for i in range(num_cols)
    })
    write_deltalake(
            table_or_uri=delta_dir,
            data=table,
            mode='append',
            schema=schema)

results = duckdb.query(f"SELECT * FROM delta_scan('{delta_dir}') WHERE x32 = 101")
print(results)
```

File: kernel/src/scan/data_skipping.rs [hunk 1]
```diff
@@ -75,6 +75,36 @@ impl DataSkippingFilter {
...
+                            metadata: field.metadata.clone(),
+                        }),
+                    },
+                    Owned(data_type) => Owned(StructField {
+                        name: field.name.clone(),
+                        data_type,
+                        nullable: true,
+                        metadata: field.metadata.clone(),
+                    }),
+                };
```
Comment (scovich) [inline kernel/src/scan/data_skipping.rs:103]: There's a fair amount of redundancy here, I wonder if we can do something more streamlined?
```suggestion
                let field = match self.transform(&field.data_type)? {
                    Borrowed(data_type) if field.is_nullable() => Borrowed(field),
                    data_type => Owned(StructField {
                        name: field.name.clone(),
                        data_type: data_type.into_owned(),
                        nullable: true,
                        metadata: field.metadata.clone(),
                    }),
                };
```

File: kernel/tests/read.rs [hunk 2]
```diff
@@ -906,6 +907,71 @@ fn with_predicate_and_removes() -> Result<(), Box<dyn std::error::Error>> {
...
+    let engine = Arc::new(DefaultEngine::new(
+        storage.clone(),
+        Path::from("/"),
+        Arc::new(TokioBackgroundExecutor::new()),
+    ));
+
+    let table = Table::new(location);
+    let snapshot = Arc::new(table.snapshot(engine.as_ref(), None)?);
+
+    let predicate = Expression::eq(column_expr!("id"), 2);
```
Comment (scovich) [inline kernel/tests/read.rs:955]: Kernel doesn't support partition pruning quite yet, so this expression will not have any filtering power. 
I'd expect an assertion failure below, because both files were scanned.

File: kernel/tests/read.rs [hunk 3]
```diff
@@ -906,6 +907,71 @@ fn with_predicate_and_removes() -> Result<(), Box<dyn std::error::Error>> {
     Ok(())
 }
 
+#[tokio::test]
+async fn predicate_on_non_nullable_partition_col() -> Result<(), Box<dyn std::error::Error>> {
```
Comment (scovich) [inline kernel/tests/read.rs:911]: Given that stats are also optional even for non-nullable data columns, should we also make `val` non-nullable and have one of the files missing stats for it?

**Review by scovich — COMMENTED** [review]
Thanks for tackling this, the approach looks good. Couple questions tho.

File: kernel/tests/read.rs (hunk 2 above)
Comment (scovich) [reply kernel/tests/read.rs:955]: Update: I didn't notice at first, but the add actions provide min/max stats for the partition columns. So the test passes because stats pruning kicks in even tho partition pruning does not. 

While this is technically legal, it's unusual/unexpected. Maybe better to split out the two scenarios? 

One test only checks `id` (which lack stats in all files and so no files get pruned until partition pruning support lands).

The other test only checks `val` (which lacks stats in one file so that file doesn't get pruned even tho the predicate "should" eliminate it).

File: kernel/src/scan/data_skipping.rs (hunk 1 above)
Comment (adamreeve) [reply kernel/src/scan/data_skipping.rs]: Good point, that's much nicer thanks.

File: kernel/tests/read.rs (hunk 3 above)
Comment (adamreeve) [reply kernel/tests/read.rs]: Yeah good idea, I've updated the test to do this and also tested with a predicate on the `val` column.

File: kernel/tests/read.rs (hunk 2 above)
Comment (adamreeve) [reply kernel/tests/read.rs]: I'm not quite following. The min/max stats aren't present in the JSON `add` actions used by the test. I was assuming there's a later step after the `DataSkippingFilter` is applied that filters all the rows from the batch where the predicate returns false and so skips the batch after the file is read, but I'm getting a bit lost trying to debug this and understand what's happening at the moment.

Comment (adamreeve) [reply kernel/tests/read.rs]: Ah, the problem was that I was writing the id column to the Parquet files, and so the min and max were stored in the Parquet row group stats and these row groups were filtered out. So this wasn't very representative of an actual partition field, whoops. Yeah splitting this out to two tests is probably best, I'll do that.

Comment (adamreeve) [reply kernel/tests/read.rs]: OK this should be fixed now, thanks for catching this!

**Review by scovich — APPROVED** [review]
Very nice, thanks for fixing this!

File: kernel/tests/read.rs [hunk 4]
```diff
@@ -906,6 +908,129 @@ fn with_predicate_and_removes() -> Result<(), Box<dyn std::error::Error>> {
     Ok(())
 }
 
+#[tokio::test]
+async fn predicate_on_non_nullable_partition_column() -> Result<(), Box<dyn std::error::Error>> {
+    // Test for https://github.com/delta-io/delta-kernel-rs/issues/698
```
Comment (zachschuermann) [inline kernel/tests/read.rs:913]: nice, thanks for adding test!

**Review by zachschuermann — APPROVED** [review]
LGTM thanks for catching + fixing this!!
