### PR TITLE
fix: remove azure suffix range request

### LINKED ISSUE #968: IO Error: DeltKernel ParquetError (7): Arrow error: External: Operation not supported: Azure does not support suffix range requests
### Describe the bug

I am cross posting here, as I think it is a related issue, when duckdb upgraded the kernel to 0.10, I start getting this kind of errors from delta,  i test it today with a table hosted in azure and managed by databricks and got the same error

IO Error: DeltKernel ParquetError (7): Arrow error: External: Operation not supported: Azure does not support suffix range requests

https://github.com/duckdb/duckdb-delta/issues/191

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zachschuermann**
resolves #968 (I hope)

## What changes are proposed in this pull request?
TLDR: Fixes kernel (default-engine) error when trying to read on azure.

`arrow-55` introduced [support for reading parquet metadata via suffix range requests](https://github.com/apache/arrow-rs/pull/7334) but since azure [doesn't support suffix range requests](https://github.com/apache/arrow-rs-object-store/blob/9c43521d3c8e86fdfc4df788a5a63e45e23093b7/src/azure/client.rs#L912-L918) whenever anyone tried reading an azure table with default-engine based on arrow-55 it [blew up](https://github.com/delta-io/delta-kernel-rs/issues/968).

This PR mitigates by re-adding the original `head` request so that we can pass the `file_size` to the `ParquetObjectReader::with_file_size` which states that when this API is used, the reader will ensure only bounded range requests are used:
```rust
/// Provide the byte size of this file.
///
/// If provided, the file size will ensure that only bounded range requests are used. If file
/// size is not provided, the reader will use suffix range requests to fetch the metadata.
///
/// Providing this size up front is an important optimization to avoid extra calls when the
/// underlying store does not support suffix range requests.
///
/// The file size can be obtained using [`ObjectStore::list`] or [`ObjectStore::head`].
pub fn with_file_size(self, file_size: usize) -> Self { ... }
```

## How was this change tested?
tested manually.. painfully manually. spun up a public azure container thing and pointed our example code at it. was able to repro the following error without my changes and observe it going away after changes here applied.
```
Parquet(
    External(
        NotSupported {
            source: "Azure does not support suffix range requests",
        },
    ),
)
```

obviously highlights our test gap. working on setting up some environments to test against S3/ADLS/GCS/etc.

### CODE REVIEW

File: kernel/src/engine/default/parquet.rs [hunk 1]
```diff
@@ -265,7 +265,22 @@ impl FileOpener for ParquetOpener {
...
+                // HACK: unfortunately, `ParquetObjectReader` under the hood does a suffix range
+                // request which isn't supported by Azure. For now we just detect if the URL is
+                // pointing to azure and if so, do a HEAD request so we can pass in file size to the
+                // reader which will cause the reader to avoid a suffix range request.
+                // see also: https://github.com/delta-io/delta-kernel-rs/issues/968
+                if let Ok((ObjectStoreScheme::MicrosoftAzure, _)) =
+                    ObjectStoreScheme::parse(&file_meta.location)
+                {
+                    let meta = store.head(&path).await?;
+                    ParquetObjectReader::new(store, path).with_file_size(meta.size)
```
Comment (scovich) [inline kernel/src/engine/default/parquet.rs:285]: Can we avoid the complexity (and HEAD request) by an unconditional `with_file_size(file_meta.size)`? Seems highly doubtful it would hurt performance on the non-azure cloud stores.

Unless we worry the passed size could be inaccurate? (if so, we should just fix that)

(from what I understand, before arrow-55 we needed an `ObjectMeta` that requires a superset of the information available from our `FileMeta` -- but now we just need the size).

Aside: object store API has a flaw, in case files could be modified concurrently. Without the ability to pass an etag/version/modtime as verification, even a HEAD immediately followed by a GET risks a bad read because the file changed between the two calls.

Comment (nicklan) [reply kernel/src/engine/default/parquet.rs:285]: I can confirm that (after fixing all the annoying listing/container issues), using `file_meta.size` does work (at least for one test case)

Comment (zachschuermann) [reply kernel/src/engine/default/parquet.rs:285]: yup thanks :) I probably should have done that to start.. right now i'm just fixing some UT that I think have incorrect sizes

Comment (zachschuermann) [reply kernel/src/engine/default/parquet.rs:285]: well regrettably moving to always including `file_meta.size` is a moderately large lift due to two things I ran across:
1. handful of UT that hardcode size = 0, relatively easy fix maybe 100LOC total
2. CDF's `execute`/`read_scan_file` API bakes in [file_size = 0](https://github.com/delta-io/delta-kernel-rs/blob/bf012fc56ef9daf5ca3a5247fb3ebc9de7eb0af6/kernel/src/table_changes/scan.rs#L302) which means we need to update the [`CDF_SCAN_ROW_SCHEMA`](https://github.com/delta-io/delta-kernel-rs/blob/bf012fc56ef9daf5ca3a5247fb3ebc9de7eb0af6/kernel/src/table_changes/scan_file.rs#L177) to plumb through `size` and then ultimately consume that in `read_scan_file`. this is the larger lift which probably should be orthogonal to the fix we are trying to implement here

@scovich @nicklan how do you feel about keeping these changes as an immediate mitigation then taking on the "always plumb through file size" as a follow up?

Comment (scovich) [reply kernel/src/engine/default/parquet.rs:285]: I'm fine either way, with a slight preference toward fixing the CDF as a pre-req PR (I suspect it's not actually a big lift, hard part will be reworking all the visitor indexes to account for the new schema fields).

Comment (scovich) [reply kernel/src/engine/default/parquet.rs:285]: TODO comment + issue and call it good?

**Review by scovich — APPROVED** [review]
LGTM, one quick suggestion

File: kernel/src/engine/default/parquet.rs (hunk 1 above)
Comment (zachschuermann) [reply kernel/src/engine/default/parquet.rs:285]: sounds good, spent a moment on this but yea probably better to just punt a little and ship the mitigation. I made #1010 for tracking this and went ahead and tossed my WIP PR here #1011

**Review by nicklan — APPROVED** [review]
