### PR TITLE
fix: Don't return errors from ParsedLogPath::try_from

### LINKED ISSUE #1432: InvalidLogPath Error when reading Deltalake from Databricks.
### Describe the bug

When I attempted to read a Deltalake table from Databricks, I get an InvalidLogPath error related to what appears to be some Databricks specific files. i.e. `.../_delta_log/_copy_into_log/0.zip`.

### To Reproduce

I copied the structure with some dummy files in a local Deltalake directory, which reproduces the issue.

To reproduce, use the `delta-kernel-rs\kernel\examples\read-table-single-threaded` example, and read from the attached Deltalake directory.

Error log w/ Repro:
```
Reading file:///D:/code/python/tmp/some-table/
InvalidLogPath(
    "file:///D:/code/python/tmp/some-table/_delta_log/_copy_into_log/0.zip",
)
```

[some-table.zip](https://github.com/user-attachments/files/23195699/some-table.zip)

### Expected behavior

The table should be read correctly, instead of erroring due to the presence of the `_copy_into_log` directory.

Expected output:
```
Reading file:///D:/code/python/tmp/some-table/
+-----+--------+
| num | letter |
+-----+--------+
| 1   | a      |
| 2   | b      |
| 3   | c      |
+-----+--------+
```

### Additional context

* The `_copy_into_log` directory sounds likely to be related to the `COPY INTO` command on Databricks.
* It does not appear to be related to Deltalake at all, so maybe it can be excluded from the list of files to be parsed somehow?

### PR DESCRIPTION
**Pull request by nicklan**
## What changes are proposed in this pull request?
This change effectively makes log path parsing infallible. We no longer return errors from `ParsedLogPath::try_from`. This fixes #1432.

This _also_ turns any valid looking files that aren't in an expected subdir to be of "Unknown" type.  (either `_delta_log` for most everything except `_staged_commits` for staged files)

As a follow-up we need to _actually_ just return an `Option<ParsedLogPath<Location>>` from that method. Doing so requires numerous tricky changes in our log listing code and I wanted to get a more targeted fix in for the issue and then we can tackle the refactor at a more leisurely pace. At that time I think we could also clean up the `try_from` method logic to make it a bit more clear, but again I didn't want to make large changes close to release.

## How was this change tested?
Modified existing unit tests, added a new test in `read.rs` that we can read a table with a `0.zip` file in the log dir.

### CODE REVIEW

File: kernel/tests/read.rs [hunk 1]
```diff
@@ -1533,3 +1533,45 @@ async fn test_unsupported_metadata_columns() -> Result<(), Box<dyn std::error::E
...
+    storage
+        .put(
+            &Path::from(PARQUET_FILE2),
+            record_batch_to_bytes(&batch).into(),
+        )
+        .await?;
+
+    // add a file that starts with a number, but isn't a valid version, we should just skip it
+    storage
+        .put(&Path::from("_delta_log/0.zip"), vec![1u8].into())
```
Comment (zachschuermann) [inline kernel/tests/read.rs]: could maybe also include a test for `_delta_log/_copy_into_log/0.zip` in case we think that extra dir provides another useful test?

Comment (nicklan) [reply kernel/tests/read.rs]: Good call! I actually added a bunch of "odd" paths to check which made me discover that we weren't ignoring "valid" files that were in random subdirs. So I've now added that and tests for it.

File: kernel/src/path.rs [hunk 2]
```diff
@@ -137,33 +138,43 @@ impl<Location: AsUrl> ParsedLogPath<Location> {
             None => return Ok(None),
         };
 
+        let in_root_dir = subdir == Some("_delta_log");
```
Comment (OussamaSaoudi) [inline kernel/src/path.rs]: For this table, I always think of the root directory as `my_table`, not `my_table/_delta_log`. AFAIK this is the standard we use throughout the code.
```
my_table/_delta_log/0000000000000000000.json
my_table/_delta_log/0000000000000000001.json
```
```suggestion
        let in_delta_log_dir = subdir == Some("_delta_log");
```

File: kernel/tests/read.rs [hunk 3]
```diff
@@ -1533,3 +1533,63 @@ async fn test_unsupported_metadata_columns() -> Result<(), Box<dyn std::error::E
...
+        "_delta_log/_and_me/00000000000000000000.checkpoint.parquet",
+        "_delta_log/02184.json",
+        "_delta_log/0x000000000000000000.checkpoint.parquet",
+        "00000000000000000000.json",
+    ];
+
+    for invalid_file in invalid_files.iter() {
+        let invalid_path = Path::from(*invalid_file);
+        storage.put(&invalid_path, vec![1u8].into()).await?;
+        let _ = Snapshot::builder_for(location.clone()).build(engine.as_ref())?;
```
Comment (OussamaSaoudi) [inline kernel/tests/read.rs]: Can you verify that Snapshot.log_segment never contains any of these?

File: kernel/src/path.rs [hunk 4]
```diff
@@ -70,11 +70,12 @@ pub(crate) struct ParsedLogPath<Location: AsUrl = FileMeta> {
...
 
 // Internal helper used by TryFrom<FileMeta> below. It parses a fixed-length string into the numeric
-// type expected by the caller. A wrong length produces an error, even if the parse succeeded.
-fn parse_path_part<T: FromStr>(value: &str, expect_len: usize, location: &Url) -> DeltaResult<T> {
+// type expected by the caller. A parsing failure returns None. A wrong length produces None, even
+// if the parse succeeded.
+fn parse_path_part<T: FromStr>(value: &str, expect_len: usize) -> Option<T> {
     match value.parse() {
-        Ok(result) if value.len() == expect_len => Ok(result),
-        _ => Err(Error::invalid_log_path(location)),
```
Comment (OussamaSaoudi) [inline kernel/src/path.rs:77]: Do we still need the `invalid_log_path` variant? If not, let's go ahead and remove it. Otherwise, disregard.

File: kernel/src/path.rs [hunk 5]
```diff
@@ -137,33 +138,43 @@ impl<Location: AsUrl> ParsedLogPath<Location> {
             None => return Ok(None),
         };
 
+        let in_root_dir = subdir == Some("_delta_log");
+
         // Parse the file type, based on the number of remaining parts
         let file_type = match split.as_slice() {
-            ["json"] => LogPathFileType::Commit,
+            ["json"] if in_root_dir => LogPathFileType::Commit,
             [uuid, "json"] if subdir == Some("_staged_commits") => {
```
Comment (OussamaSaoudi) [inline kernel/src/path.rs]: I just realized that this could be error prone. Example:
```
_delta_log/my_random_dir/_staged_commits/...
```

By protocol, I don't think we want to read this. But this subdir check allows it. Given that this PR makes us more flexible, I reckon we should handle that case and ignore.

Comment (OussamaSaoudi) [reply kernel/src/path.rs]: Ah can we also add this case to the test below?

File: kernel/tests/read.rs (hunk 3 above)
Comment (nicklan) [reply kernel/tests/read.rs]: Yep, done. was a bit more tricky than expected :)

File: kernel/src/path.rs (hunk 5 above)
Comment (nicklan) [reply kernel/src/path.rs]: Yeah, great catch. 

It's actually kinda complex. Like if there was a dir like: `foo/_delta_log/another_table/_delta_log`, should we consider foo/_delta_log/another_table to be a valid path to a delta table? Actually with our current code, we cannot allow this and still correctly read foo as a valid path, because we don't know in the context of a single path which table we're trying to read so I'm going to say "no" to the above question for now, because such a directory would break things if we tried to allow it, and we'll need to introduce more context for try_from in the future if we do want to allow it.

It would be up to the earlier code to potentially strip off anything before the delta log dir if we wanted to support nested tables like that

File: kernel/src/path.rs (hunk 4 above)
Comment (nicklan) [reply kernel/src/path.rs:77]: Yeah, we still have it in `log_path.rs` where we want to require that the type isn't "unknown" and return `invalid_log_path` if it is unknown.

File: kernel/src/path.rs [hunk 6]
```diff
@@ -97,22 +98,26 @@ impl AsUrl for Url {
     }
 }
 
+fn path_contains_delta_log_dir(mut path_segments: std::str::Split<'_, char>) -> bool {
+    path_segments.any(|p| p == "_delta_log")
```
Comment (zachschuermann) [inline kernel/src/path.rs]: mega nit but we could maybe recycle `DELTA_LOG_DIR` const? but i guess we don't want it with the trailing '/'..

File: kernel/src/path.rs [hunk 7]
```diff
@@ -137,33 +142,66 @@ impl<Location: AsUrl> ParsedLogPath<Location> {
...
+        } else {
+            (
+                subdir == Some("_delta_log") && !path_contains_delta_log_dir(path_segments),
+                false,
+            )
+        };
+
+        println!(
+            "For {url:?} is_delta_log_dir {in_delta_log_dir}, is_staged {in_staged_commits_dir}"
+        );
```
Comment (zachschuermann) [inline kernel/src/path.rs]:
```suggestion
```

File: kernel/src/path.rs [hunk 8]
```diff
@@ -137,33 +142,66 @@ impl<Location: AsUrl> ParsedLogPath<Location> {
...
+                (false, true)
+            } else {
+                (false, false)
+            }
+        } else {
+            (
+                subdir == Some("_delta_log") && !path_contains_delta_log_dir(path_segments),
+                false,
+            )
+        };
```
Comment (zachschuermann) [inline kernel/src/path.rs:165]: should we (could we?) instead just expand the parsing/matching below to just do `_delta_log/number.json` = commit, etc etc.?

like instead of doing all this ahead of time would it be easier to embed in the `match`?

File: kernel/tests/read.rs [hunk 9]
```diff
@@ -1533,3 +1535,112 @@ async fn test_unsupported_metadata_columns() -> Result<(), Box<dyn std::error::E
...
+    let invalid_files = [
+        "_delta_log/0.zip",
+        "_delta_log/_copy_into_log/0.zip",
+        "_delta_log/_ignore_me/00000000000000000000.json",
+        "_delta_log/_and_me/00000000000000000000.checkpoint.parquet",
+        "_delta_log/02184.json",
+        "_delta_log/0x000000000000000000.checkpoint.parquet",
+        "00000000000000000000.json",
+        "_delta_log/my_random_dir/_staged_commits/00000000000000000000.3a0d65cd-4056-49b8-937b-95f9e3ee90e5.json",
+        "_delta_log/my_random_dir/_delta_log/_staged_commits/00000000000000000000.3a0d65cd-4056-49b8-937b-95f9e3ee90e5.json",
```
Comment (zachschuermann) [inline kernel/tests/read.rs:1582]: maybe add a double `_staged_commits` test?

**Review by zachschuermann — APPROVED** [review]
looks good, few suggestions but going ahead and stamping!

File: kernel/src/path.rs [hunk 10]
```diff
@@ -97,22 +98,26 @@ impl AsUrl for Url {
...
 
+fn path_contains_delta_log_dir(mut path_segments: std::str::Split<'_, char>) -> bool {
+    path_segments.any(|p| p == "_delta_log")
+}
+
 impl<Location: AsUrl> ParsedLogPath<Location> {
     // NOTE: We can't actually impl TryFrom because Option<T> is a foreign struct even if T is local.
     #[internal_api]
     pub(crate) fn try_from(location: Location) -> DeltaResult<Option<ParsedLogPath<Location>>> {
         let url = location.as_url();
```
Comment (OussamaSaoudi) [inline kernel/src/path.rs:110]: It seems like we never return `Err`? Why keep this as `DeltaResult<Option<>>`

And in fact, why make this Return None for some things and LogFilePath::Unknown for others? The semantics of this function aren't clear to me. Could you either:
1) Make it always return ParsedLogPath. Weird files are considered unknown.
2) Document clearly what Ok(Some(Unknown)) vs Ok(None) means.

File: kernel/src/path.rs (hunk 8 above)
Comment (OussamaSaoudi) [inline kernel/src/path.rs:165]: The logic initially felt complicated. I think we can simplify be early returning for paths that contain multiple `_delta_log`, or for paths that don't fit into either `staged_commits` or `_delta_log`
```suggestion
        let subdir_parent = path_segments.next_back();
        if path_contains_delta_log_dir(path_segments) {
            // return weird/invalid path
        } 

        let is_delta_log_dir = match (subdir_parent, subdir) => {
            // is_delta_dir == FALSE if the file is in the `_delta_log/_staged_commits` directory
            (Some("_delta_log"), Some("_staged_commits")) => false, 
            // is_delta_dir == TRUE if the file is in the `_delta_log` directory
            (_, Some("_delta_log") => true,
            // Otherwise, the path is invalid. Early return.
            _ => {
                // Return unknown path.
            } 
            
        }
```

Comment (nicklan) [reply kernel/src/path.rs:165]: Nope, because we've already split the path, and I don't want to deal with different path separators etc. Also, we need to do the lookback to ensure we don't have a higher level `_delta_log` dir.

Comment (OussamaSaoudi) [reply kernel/src/path.rs:165]: Files we're interested in are either delta log dir, or staged commit dir. All others are inevitably going to be Unknown/Invalid.

File: kernel/src/path.rs (hunk 6 above)
Comment (nicklan) [reply kernel/src/path.rs]: yep, had to add a new variable because it matters if it has a slash after or not

File: kernel/src/path.rs (hunk 10 above)
Comment (nicklan) [reply kernel/src/path.rs:110]: Yeah, as I noted in the PR description, this isn't ideal. It should just return an option, but that's a much bigger change because it propagates up the stack and some of our iterator code is a bit hairy in how it deals with the return value here.

So I was proposing that we keep it like this in the short term where there's no semantic difference between `None` and `Some(Unknown)`, and then unify all that post 0.17. 

I can add a comment to that effect in the code if you think it's needed.

File: kernel/src/path.rs (hunk 8 above)
Comment (nicklan) [reply kernel/src/path.rs:165]: Agree it could be simpler. In the end your suggested code has to be:

```rust
        let subdir_parent = path_segments.next_back();
        let mut in_staged_commits_dir = false;
        let mut in_delta_log_dir = match (subdir_parent, subdir) {
            // in_delta_log_dir == false if the file is in the `_delta_log/_staged_commits` directory
            (Some("_delta_log"), Some("_staged_commits")) => {
                in_staged_commits_dir = true;
                false
            }
            // is_delta_dir == true if the file is in the `_delta_log` directory
            (_, Some("_delta_log")) if subdir_parent != Some("_delta_log")=> true,
            // Otherwise, the path is invalid. Early return.
            _ => {
                false
            }
        };

        if path_contains_delta_log_dir(path_segments) {
            // invalid as we are too deep in a tree with a `_delta_log` directory above us
            in_delta_log_dir = false;
            in_staged_commits_dir = false;
        }
```

To maintain the semantics the calling code expects, which I'm not sure is significantly simpler anymore. This should all be simplified when we refactor.

**Comment by nicklan** [comment]
created #1444 as a follow-up

**Comment by nicklan** [comment]
The docs error is odd, it works locally for me and the item does seem to exist. Going to go ahead and merge and we can take up root-causing that as a follow-up
