### PR TITLE
test: Assert tests on error message instead of `is_err()`

### LINKED ISSUE #999: Replace `is_err` checks with error type/msg matching
Current implementation of unit tests often check errors by a simple `assert!(_.is_err())`. Instead, it would be more precise to make assertion statements that match the exact error type. For instance,
```rust
fn test_non_contiguous_log() {
    // Commit with version 1 is missing
    let (storage, log_root) = build_log_with_paths_and_checkpoint(
        &[
            delta_path_for_version(0, "json"),
            delta_path_for_version(2, "json"),
        ],
        None,
    );

    let log_segment_res =
        LogSegment::for_table_changes(storage.as_ref(), log_root.clone(), 0, None);
    assert!(log_segment_res.is_err());
    // Could be replaced with:
    // assert!(matches!(
    //      log_segment_res, 
    //      Err(Error::Generic(msg)) if msg == expectedMsg
    //  ));
    
    ...
}
```

### PR DESCRIPTION
**Pull request by joonyoo181**
## What changes are proposed in this pull request?

fixes #999 

This PR:
- creates a util function for checking error messages on types `Result<T, E: ToString>` using `contain()`
- refactors existing test cases to use the new utility function instead of `is_err()`

## How was this change tested?

I ran `cargo nextest run` and passed all tests

### CODE REVIEW

**Review by zachschuermann — COMMENTED** [review]
looks great! could we avoid pulling in `regex` by just doing `contains` on the error message instead? seems that would handle most (all?) cases well enough?

File: kernel/src/actions/mod.rs [hunk 1]
```diff
@@ -1115,7 +1116,10 @@ mod tests {
             Some([ReaderFeature::V2Checkpoint]),
         )
         .unwrap();
-        assert!(protocol.ensure_read_supported().is_err());
+        assert_result_error_with_message(
```
Comment (zachschuermann) [inline kernel/src/actions/mod.rs]: (i realize this is old code - but maybe can take the chance to fix up)

feels like we should just delete this? not sure what value it has?

File: kernel/src/engine/ensure_data_types.rs [hunk 2]
```diff
@@ -381,23 +386,26 @@ mod tests {
...
+            ),
+            "Generic delta kernel error: Map has nullablily false in kernel and true in arrow",
+        );
+        assert_result_error_with_message(
+            ensure_data_types(
+                &DataType::Map(Box::new(MapType::new(DataType::LONG, DataType::LONG, true))),
+                arrow_field.data_type(),
+                false,
+            ),
+            "Invalid argument error: Incorrect datatype. Expected long, got Utf8",
```
Comment (zachschuermann) [inline kernel/src/engine/ensure_data_types.rs:407]: in the future it would be nice to make this include context like it coming from a Map etc.? maybe make follow up issue?

File: kernel/src/log_segment/tests.rs [hunk 3]
```diff
@@ -769,14 +772,19 @@ fn test_non_contiguous_log() {
...
         LogSegment::for_table_changes(storage.as_ref(), log_root.clone(), 1, None);
-    assert!(log_segment_res.is_err());
+    assert_result_error_with_message(
+        log_segment_res,
+        "Generic delta kernel error: Expected the first commit to have version 1",
+    );
 
     let log_segment_res = LogSegment::for_table_changes(storage.as_ref(), log_root, 0, Some(1));
-    assert!(log_segment_res.is_err());
+    assert_result_error_with_message(log_segment_res, "Generic delta kernel error: LogSegment end version 0 not the same as the specified end version 1");
```
Comment (zachschuermann) [inline kernel/src/log_segment/tests.rs]: line length? (more below)

File: kernel/src/log_segment/tests.rs [hunk 4]
```diff
@@ -769,14 +772,19 @@ fn test_non_contiguous_log() {
 
     let log_segment_res =
         LogSegment::for_table_changes(storage.as_ref(), log_root.clone(), 0, None);
-    assert!(log_segment_res.is_err());
+    // check the error message up to the timestamp
+    let expected_error_pattern = r#"Generic delta kernel error: Expected ordered contiguous commit files [ParsedLogPath { location: FileMeta { location: Url { scheme: "memory", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/_delta_log/00000000000000000000.json", query: None, fragment: None }, last_modified:"#;
```
Comment (zachschuermann) [inline kernel/src/log_segment/tests.rs]: line length

File: kernel/src/log_segment/tests.rs [hunk 5]
```diff
@@ -491,7 +494,7 @@ fn build_snapshot_with_bad_checkpoint_hint_fails() {
 
     let log_segment =
         LogSegment::for_snapshot(storage.as_ref(), log_root, checkpoint_metadata, None);
-    assert!(log_segment.is_err())
+    assert_result_error_with_message(log_segment, "Invalid Checkpoint: _last_checkpoint indicated that checkpoint should have 1 parts, but it has 2")
```
Comment (zachschuermann) [inline kernel/src/log_segment/tests.rs]: line length

**Review by zachschuermann — APPROVED** [review]
LGTM just few quick things and probably could use some more line breaks :)

**Review by OussamaSaoudi — APPROVED** [review]
